apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: befunge-node-deployment
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: befungenode
   template:
     metadata:
       labels:
         app: befungenode
     spec:
       containers:
       - name: befungenode